/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        bg2: "var(--bg2)",
        card: "var(--card)",
        card2: "var(--card2)",
        border: "var(--border)",
        text1: "var(--text1)",
        text2: "var(--text2)",
        text3: "var(--text3)",
        accent: "var(--accent)",
        accentLight: "var(--accent-light)",
        green: "var(--green)",
        greenLight: "var(--green-light)",
        amber: "var(--amber)",
        amberLight: "var(--amber-light)",
        red: "var(--red)",
        redLight: "var(--red-light)",
        sage: "var(--sage)",
        sageLight: "var(--sage-light)",
        dusk: "var(--dusk)",
        duskLight: "var(--dusk-light)",
        blue: "var(--blue)",
        blueLight: "var(--blue-light)",
        gold: "var(--gold)",
        goldLight: "var(--gold-light)",
      },
      borderRadius: {
        md: "14px",
        lg: "20px",
        hero: "22px",
        pill: "30px",
      },
      fontFamily: {
        heading: ["Lora_400Regular"],
        body: ["DMSans_400Regular"],
        bodyMedium: ["DMSans_500Medium"],
        bodySemi: ["DMSans_600SemiBold"],
      },
    },
  },
  plugins: [],
};
